### ISSUE TITLE
Adapter is not returning uploaded images

### ISSUE THREAD

**Issue by lulufan-12** [captbrogers/ghost-minio#8]
Adapter is uploading the images to Minio Server correctly but it doesn't get them. It only shows a blank square.
Next monday, I will try fix this issue but if someone already faced this problem, let me know.

**Comment by kittizz** [comment]
I think the path where those images are stored must be publicly accessible.

**Comment by captbrogers** [comment]
I haven't looked at this code in a long while but I will try to check on it later this week. However, if you find there is a bug then any information is appreciated. Thanks.

**Comment by lulufan-12** [comment]
No issue, storage wasn't public, that's why I was getting a 401.
